version: '3.8'

services:
  api:
    container_name: netrin_challenge
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: flask --app api/main/configs/app.py run --host=0.0.0.0 --port ${API_PORT:-8000}
    user: root
    volumes:
      - .:/app/
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - ./.env.dev